# Spaces on the board, in order from GO
spaces:
  '0':
    type: 'go'
  '1':
    type: 'property'
    name: 'Mediterranean Avenue'
    price: 60
    rent: '2,10,30,90,160,250'
    houseprice: 50
    color: 'd'
  '2':
    type: 'communitychest'
  '3':
    type: 'property'
    name: 'Baltic Avenue'
    price: 60
    rent: '4,20,60,180,320,450'
    houseprice: 50
    color: 'd'
  '4':
    type: 'tax'
    name: 'Income'
    price: 200
  '5':
    type: 'railroad'
    name: 'Reading Railroad'
    price: 200
    rent: '25,50,100,200'
    color: '7'
  '6':
    type: 'property'
    name: 'Oriental Avenue'
    price: 100
    rent: '6,30,90,270,400,550'
    houseprice: 50
    color: '3'
  '7':
    type: 'chance'
  '8':
    type: 'property'
    name: 'Vermont Avenue'
    price: 100
    rent: '6,30,90,270,400,550'
    houseprice: 50
    color: '3'
  '9':
    type: 'property'
    name: 'Connecticut Avenue'
    price: 120
    rent: '8,40,100,300,450,600'
    houseprice: 50
    color: '3'
  '10':
    type: 'jail'
  '11':
    type: 'property'
    name: 'St. Charles Places'
    price: 140
    rent: '10,50,150,450,625,750'
    houseprice: 100
    color: '5'
  '12':
    type: 'utility'
    name: 'Electric Company'
    price: 150
    rent: '4,10'
    color: '8'
  '13':
    type: 'property'
    name: 'States Avenue'
    price: 140
    rent: '10,50,150,450,625,750'
    houseprice: 100
    color: '5'
  '14':
    type: 'property'
    name: 'Virginia Avenue'
    price: 160
    rent: '12,60,180,500,700,900'
    houseprice: 100
    color: '5'
  '15':
    type: 'railroad'
    name: 'Pennsylvania Railroad'
    price: 200
    rent: '25,50,100,200'
    color: '7'
  '16':
    type: 'property'
    name: 'St. James Places'
    price: 180
    rent: '14,70,200,550,750,950'
    houseprice: 100
    color: '6'
  '17':
    type: 'communitychest'
  '18':
    type: 'property'
    name: 'Tennessee Avenue'
    price: 180
    rent: '14,70,200,550,750,950'
    houseprice: 100
    color: '6'
  '19':
    type: 'property'
    name: 'New York Avenue'
    price: 200
    rent: '16,80,220,600,800,1000'
    houseprice: 100
    color: '6'
  '20':
    type: 'free'
  '21':
    type: 'property'
    name: 'Kentucky Avenue'
    price: 220
    rent: '18,90,250,700,875,1050'
    houseprice: 150
    color: '4'
  '22':
    type: 'chance'
  '23':
    type: 'property'
    name: 'Indiana Avenue'
    price: 220
    rent: '18,90,250,700,875,1050'
    houseprice: 150
    color: '4'
  '24':
    type: 'property'
    name: 'Illinois Avenue'
    price: 240
    rent: '20,100,300,750,925,1100'
    houseprice: 150
    color: '4'
  '25':
    type: 'railroad'
    name: 'B. & O. Railroad'
    price: 200
    rent: '25,50,100,200'
    color: '7'
  '26':
    type: 'property'
    name: 'Atlantic Avenue'
    price: 260
    rent: '22,110,330,800,975,1150'
    houseprice: 150
    color: 'e'
  '27':
    type: 'property'
    name: 'Ventnor Avenue'
    price: 260
    rent: '22,110,330,800,975,1150'
    houseprice: 150
    color: 'e'
  '28':
    type: 'utility'
    name: 'Water Works'
    price: 150
    rent: '4,10'
    color: '8'
  '29':
    type: 'property'
    name: 'Marvin Gardens'
    price: 280
    rent: '24,120,360,850,1025,1200'
    houseprice: 150
    color: 'e'
  '30':
    type: 'gotojail'
  '31':
    type: 'property'
    name: 'Pacific Avenue'
    price: 300
    rent: '26,130,390,900,1100,1275'
    houseprice: 200
    color: '2'
  '32':
    type: 'property'
    name: 'North Carolina Avenue'
    price: 300
    rent: '26,130,390,900,1100,1275'
    houseprice: 200
    color: '2'
  '33':
    type: 'communitychest'
  '34':
    type: 'property'
    name: 'Pennsylvania Avenua'
    price: 320
    rent: '28,150,450,1000,1200,1400'
    houseprice: 200
    color: '2'
  '35':
    type: 'railroad'
    name: 'Short Line'
    price: 200
    rent: '25,50,100,200'
    color: '7'
  '36':
    type: 'chance'
  '37':
    type: 'property'
    name: 'Park Place'
    price: 350
    rent: '35,175,500,1100,1300,1500'
    houseprice: 200
    color: '9'
  '38':
    type: 'tax'
    name: 'Luxury'
    price: 100
  '39':
    type: 'property'
    name: 'Boardwalk'
    price: 400
    rent: '50,200,600,1400,1700,2000'
    houseprice: 200
    color: '9'
    
# Community Chest Cards
communitychest:
  '0':
    type: 'move'
    name: 'Advance to Go'
    move: 0
  '1':
    type: 'gainmoney'
    name: 'Bank error in your favor. Collect $200.'
    amount: 200
  '2':
    type: 'losemoney'
    name: "Doctor's fees. Pay $50."
    amount: 50
  '3':
    type: 'gainmoney'
    name: 'From sale of stock you get $50.'
    amount: 50
  '4':
    type: 'jailfree'
    name: 'Get out of jail free card.'
  '5':
    type: 'jail'
    name: 'Go to jail.'
  '6':
    type: 'takemoney'
    name: 'Grand Opera Night. Collect $50 from every player for opening night seats.'
    amount: 50
  '7':
    type: 'gainmoney'
    name: 'Holiday fund matures. Receive $100.'
    amount: 100
  '8':
    type: 'gainmoney'
    name: 'Income tax refund. Collect $20.'
    amount: 20
  '9':
    type: 'takemoney'
    name: 'It§s your birthday. Collect $10 from every player.'
    amount: 10
  '10':
    type: 'gainmoney'
    name: 'Life insurance matures. Collect $100.'
    amount: 100
  '11':
    type: 'losemoney'
    name: "Hospital fees. Pay $50."
    amount: 50
  '12':
    type: 'losemoney'
    name: "School fees. Pay $50."
    amount: 50
  '13':
    type: 'gainmoney'
    name: 'Receive $25 consultancy fee.'
    amount: 25
  '14':
    type: 'buildingtax'
    name: 'You are assessed for street repairs. Pay $40 per house and $115 per hotel you own.'
    house: 40
    hotel: 115
  '15':
    type: 'gainmoney'
    name: 'You have won second place in a beauty contest. Collect $10.'
    amount: 10
  '16':
    type: 'gainmoney'
    name: 'You inherit $100.'
    amount: 100
    
# Chance Cards
chance:
  '0':
    type: 'move'
    name: 'Advance to Go'
    move: 0
  '1':
    type: 'move'
    name: 'Advance to Illinois Avenue. If you pass Go, collect $200.'
    move: 24
  '2':
    type: 'move'
    name: 'Advance to St. Charles Place. If you pass Go, collect $200.'
    move: 11
  '2':
    type: 'nearestutility'
    name: 'Advance to nearest Utility. If owned, throw dice and pay owner a total 10x the amount thrown.'
  '3':
    type: 'nearestrailroad'
    name: 'Advance to nearest railroad and pay twice the rent.'
  '4':
    type: 'gainmoney'
    name: 'Bank pays you a dividend of $50.'
    amount: 50
  '5':
    type: 'jailfree'
    name: 'Get out of jail free card.'
  '6':
    type: 'moverelative'
    name: 'Go back three spaces.'
    move: -3
  '7':
    type: 'jail'
    name: 'Go to jail.'
  '8':
    type: 'buildingtax'
    name: 'Make general repairs on all your property. For each house pay $25, for each hotel pay $100.'
    house: 25
    hotel: 100
  '9':
    type: 'losemoney'
    name: "Speeding ticket. Pay $15."
    amount: 15
  '10':
    type: 'move'
    name: 'Take a trip to Reading Railroad. If you pass go, collect $200.'
    move: 5
  '11':
    type: 'move'
    name: 'Take a walk on the boardwalk. Advance token to Boardwalk. If you pass go, collect $200.'
    move: 39
  '12':
    type: 'paymoney'
    name: 'You have been elected Chairman of the Board. Pay each player $50.'
    amount: 50
  '13':
    type: 'gainmoney'
    name: 'Your building loan matures. Receive $150.'
    amount: 150
  '14':
    type: 'gainmoney'
    name: 'You have won a crossword competition. Collect $100.'
    amount: 100